[build]
  command = "npm --workspace apps/pokemon-detail-mf run build"
  publish = "apps/pokemon-detail-mf/dist"

[[headers]]
  for = "/assets/remoteEntry.js"
  [headers.values]
    Access-Control-Allow-Origin = "https://pokemon-shell-mf.netlify.app"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://pokemon-shell-mf.netlify.app"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200